import { getDb, generateId, updateMaterialPrice } from '@/lib/db';
import { centralFlowBlock } from '@/lib/store-engine';
import { getCurrentUser } from '@/lib/auth';
import { checkPurchaseDate } from '@/lib/purchase-guard';

interface BulkPurchaseItem {
  item_name: string;
  vendor?: string;
  brand?: string;
  quantity: number;
  unit_price: number;
  total_amount?: number;
  date: string;
  notes?: string;
  gst_amount?: number;
  /** The VENDOR's own bill number (from the physical bill). Our Invoice ID is
   *  generated by the server — it is never taken from the upload. */
  bill_no?: string;
  // GRN-Inward per-line charges (₹) — recorded only, never change unit cost.
  discount?: number; cgst?: number; sgst?: number;
  special_excise_cess?: number; tcs?: number; delivery_charges?: number; mrp_round_off?: number;
}

/** One rejected row, echoed back with enough to re-download + fix + re-upload. */
type SkipKind = 'missing' | 'date' | 'not_found' | 'liquor' | 'invalid' | 'duplicate';
interface SkippedRow {
  row: number;
  item_name: string; vendor: string; brand: string;
  quantity: any; unit_price: any; total_amount: any; gst_amount: any;
  date: string; notes: string; bill_no: string;
  discount: any; cgst: any; sgst: any; special_excise_cess: any; tcs: any; delivery_charges: any; mrp_round_off: any;
  kind: SkipKind; reason: string;
}
/** Per-line charge coercion. mrp_round_off is signed; the rest ≥ 0. */
const chg = (v: any) => { const x = Number(v); return Number.isFinite(x) && x > 0 ? Math.round(x * 100) / 100 : 0; };
const chgSigned = (v: any) => { const x = Number(v); return Number.isFinite(x) ? Math.round(x * 100) / 100 : 0; };

export async function POST(request: Request) {
  try {
    const db = getDb();
    const body = await request.json();
    const { purchases } = body as { purchases: BulkPurchaseItem[] };

    if (!purchases || !Array.isArray(purchases) || purchases.length === 0) {
      return Response.json({ error: 'purchases array is required' }, { status: 400 });
    }

    const me = await getCurrentUser();
    const isAdmin = me?.role === 'admin';

    const allMaterials = db.prepare('SELECT id, name, unit, purchase_unit, pack_size FROM raw_materials').all() as any[];
    const materialMap = new Map<string, any>();
    for (const m of allMaterials) materialMap.set(m.name.toLowerCase().trim(), m);

    const toStockQty = (m: any, qty: number) => {
      const packSize = Number(m.pack_size) || 1;
      const ru = String(m.unit || '').toLowerCase().trim();
      const pu = String(m.purchase_unit || m.unit || '').toLowerCase().trim();
      return (packSize > 1 && ru !== pu) ? qty * packSize : qty;
    };

    const results: {
      success: number; skipped: number; duplicates: number;
      errors: string[];
      store_blocked: Array<{ material: string; error: string }>;
      skipped_rows: SkippedRow[];
    } = { success: 0, skipped: 0, duplicates: 0, errors: [], store_blocked: [], skipped_rows: [] };

    // Record a skipped row into every reporting channel (back-compat + the new
    // detailed list the UI shows + lets the user download).
    const skip = (item: BulkPurchaseItem, rowNum: number, kind: SkipKind, reason: string) => {
      results.skipped++;
      if (kind === 'duplicate') results.duplicates++;
      results.errors.push(`Row ${rowNum}: ${reason}`);
      if (kind === 'liquor') results.store_blocked.push({ material: item.item_name || '', error: reason });
      results.skipped_rows.push({
        row: rowNum,
        item_name: item.item_name || '', vendor: item.vendor || '', brand: item.brand || '',
        quantity: item.quantity ?? '', unit_price: item.unit_price ?? '',
        total_amount: item.total_amount ?? '', gst_amount: item.gst_amount ?? '',
        date: item.date || '', notes: item.notes || '', bill_no: item.bill_no || '',
        discount: item.discount ?? '', cgst: item.cgst ?? '', sgst: item.sgst ?? '',
        special_excise_cess: item.special_excise_cess ?? '', tcs: item.tcs ?? '',
        delivery_charges: item.delivery_charges ?? '', mrp_round_off: item.mrp_round_off ?? '',
        kind, reason,
      });
    };

    const insertPurchase = db.prepare(`
      INSERT INTO purchases (id, material_id, vendor, brand, quantity, unit_price, total_price, date, notes, invoice_id, bill_no,
                             discount, cgst, sgst, special_excise_cess, tcs, delivery_charges, mrp_round_off, created_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
    `);

    // ── Invoice ID (OUR number) — auto-generated, never taken from the upload.
    // Format PINV-<year>-#### continuing from the highest existing number.
    // Lines of the SAME vendor bill (vendor + bill_no + date) share ONE
    // invoice_id; rows with no bill_no each get their own (we can't know they
    // belong together). Distinct from bill_no, the vendor's own bill number.
    const yr = new Date().getFullYear();
    // MAX on the NUMERIC suffix — a string sort would rank 'PINV-2026-9999'
    // above 'PINV-2026-10000' once the year passes 9,999 lines and reuse ids.
    const lastInv = db.prepare(
      `SELECT MAX(CAST(substr(invoice_id, length('PINV-' || ? || '-') + 1) AS INTEGER)) AS n
       FROM purchases WHERE invoice_id LIKE 'PINV-' || ? || '-%'`
    ).get(String(yr), String(yr)) as any;
    let invSeq = Number(lastInv?.n) || 0;
    const invoiceIdByBill = new Map<string, string>();
    // The memo Map is request-scoped, so a bill split across TWO uploads (a line
    // was missed, corrected, or split by department) would otherwise mint a
    // second id for the same physical bill. Look the bill up in the DB first.
    // COALESCE(invoice_id,'') <> '' is load-bearing: manual / GRN / PO-receive
    // rows share vendor+bill+date with an EMPTY invoice_id and must not match.
    const invoiceIdForBill = db.prepare(`
      SELECT invoice_id FROM purchases
      WHERE COALESCE(invoice_id, '') <> ''
        AND LOWER(TRIM(COALESCE(vendor, ''))) = ?
        AND LOWER(TRIM(COALESCE(bill_no, ''))) = ?
        AND date = ?
      LIMIT 1
    `);
    const mintInvoiceId = () => {
      invSeq += 1;
      return `PINV-${yr}-${String(invSeq).padStart(4, '0')}`;
    };
    const nextInvoiceId = (vendor: string, billNo: string, date: string) => {
      // No bill number → we can't know which lines belong together; solo id.
      if (!billNo) return mintInvoiceId();
      const v = (vendor || '').toLowerCase().trim();
      const b = billNo.toLowerCase().trim();
      const key = `${v}|${b}|${date}`;
      const memo = invoiceIdByBill.get(key);
      if (memo) return memo;
      const prior = invoiceIdForBill.get(v, b, date) as { invoice_id?: string } | undefined;
      const id = prior?.invoice_id || mintInvoiceId();
      invoiceIdByBill.set(key, id);
      return id;
    };
    const updateStock = db.prepare(`
      UPDATE raw_materials SET current_stock = current_stock + ?, updated_at = datetime('now') WHERE id = ?
    `);
    const insertTransaction = db.prepare(`
      INSERT INTO inventory_transactions (id, material_id, type, quantity, reference_id, notes, created_at)
      VALUES (?, ?, 'purchase', ?, ?, ?, datetime('now'))
    `);
    // Duplicate guard: same material + vendor + date + qty + unit_price already
    // in the DB, with the VENDOR's bill_no as an ADDITIONAL discriminator (never
    // our auto invoice_id, which is unique per entry and would defeat the check).
    //
    // A STORED row with an EMPTY bill_no matches ANY incoming bill_no. That is
    // load-bearing: every pre-existing row, and every row written by the single
    // POST / opening-stock / GRN / PO-receive / inward-import paths, has
    // bill_no ''. Comparing strictly would make them invisible the moment the
    // user starts filling the new bill_no column — the same file re-uploaded
    // would insert again and DOUBLE the stock. Two genuine lines that differ
    // only by a NON-empty bill number are still both kept.
    const dupCheck = db.prepare(`
      SELECT 1 FROM purchases
      WHERE material_id = ?
        AND LOWER(COALESCE(vendor, '')) = LOWER(?)
        AND (COALESCE(bill_no, '') = '' OR LOWER(bill_no) = LOWER(?))
        AND date = ?
        AND ROUND(quantity, 3)   = ROUND(?, 3)
        AND ROUND(unit_price, 2) = ROUND(?, 2)
      LIMIT 1
    `);

    const touchedMaterials = new Set<string>();
    // Also dedupe WITHIN the uploaded file (same row twice in one upload).
    const seenInFile = new Set<string>();
    const dupKey = (mid: string, vendor: string, billNo: string, date: string, q: number, up: number) =>
      `${mid}|${(vendor || '').toLowerCase().trim()}|${(billNo || '').toLowerCase().trim()}|${date}|${Math.round(q * 1000)}|${Math.round(up * 100)}`;

    const batchInsert = db.transaction(() => {
      for (let i = 0; i < purchases.length; i++) {
        const item = purchases[i];
        const rowNum = i + 1;

        if (!item.item_name || (!item.quantity && !item.total_amount) || (!item.unit_price && !item.total_amount)) {
          skip(item, rowNum, 'missing', `Missing required fields (item_name / quantity / price)`);
          continue;
        }
        const dateCheck = checkPurchaseDate(db, item.date, isAdmin);
        if (!dateCheck.ok) { skip(item, rowNum, 'date', dateCheck.error || 'Invalid date'); continue; }

        const mat = materialMap.get(item.item_name.toLowerCase().trim());
        if (!mat) { skip(item, rowNum, 'not_found', `Material not found: "${item.item_name}" — name must match an existing Raw Material.`); continue; }
        const materialId = mat.id;

        const storeMsg = centralFlowBlock(db, materialId);
        if (storeMsg) { skip(item, rowNum, 'liquor', storeMsg); continue; }

        let quantity = Number(item.quantity) || 0;
        let unitPrice = Number(item.unit_price) || 0;
        const totalAmount = Number(item.total_amount) || 0;
        const gstAmount = Number(item.gst_amount) || 0;
        // CONTRACT: total_amount is the CHARGE-FREE line amount (qty × rate).
        // It must NOT be the charge-inclusive "Total Inward Amount" — the 7
        // charges are stored separately, so folding them in here would bake
        // them into the weighted-average cost AND count them twice. The client
        // parser backs charges out before sending (see purchases/page.tsx).
        if (totalAmount > 0 && unitPrice === 0 && quantity > 0) {
          unitPrice = Math.round(((totalAmount + gstAmount) / quantity) * 100) / 100;
        }
        if (unitPrice > 0 && gstAmount > 0 && totalAmount === 0) {
          const lineTotal = unitPrice * quantity;
          unitPrice = Math.round(((lineTotal + gstAmount) / quantity) * 100) / 100;
        }
        if (quantity <= 0 || unitPrice <= 0) {
          skip(item, rowNum, 'invalid', `Invalid quantity or price for "${item.item_name}"`);
          continue;
        }

        const billNo = String(item.bill_no || '').trim();
        // Duplicate guard — already uploaded (DB) OR repeated earlier in this file.
        const key = dupKey(materialId, item.vendor || '', billNo, item.date, quantity, unitPrice);
        const already = seenInFile.has(key) || !!dupCheck.get(materialId, item.vendor || '', billNo, item.date, quantity, unitPrice);
        if (already) {
          skip(item, rowNum, 'duplicate',
            `Already uploaded — same item + vendor + bill no + date + qty + rate already exists. Skipped to avoid double-counting.`);
          continue;
        }
        seenInFile.add(key);

        const totalPrice = Math.round(quantity * unitPrice * 100) / 100;
        const id = generateId();
        const invoiceId = nextInvoiceId(item.vendor || '', billNo, item.date);
        insertPurchase.run(id, materialId, item.vendor || '', item.brand || '', quantity, unitPrice, totalPrice, item.date, item.notes || '', invoiceId, billNo,
          chg(item.discount), chg(item.cgst), chg(item.sgst), chg(item.special_excise_cess), chg(item.tcs), chg(item.delivery_charges), chgSigned(item.mrp_round_off));
        const stockQty = toStockQty(mat, quantity);
        updateStock.run(stockQty, materialId);
        insertTransaction.run(generateId(), materialId, stockQty, id, `Bulk import: ${item.vendor || 'unknown'}`);
        touchedMaterials.add(materialId);
        results.success++;
      }
    });
    batchInsert();

    for (const materialId of touchedMaterials) updateMaterialPrice(db, materialId);

    return Response.json(results, { status: 200 });
  } catch (error: any) {
    return Response.json({ error: error.message }, { status: 500 });
  }
}
