import { getDb, generateId, updateMaterialPrice } from '@/lib/db';
import { centralFlowBlock } from '@/lib/store-engine';
import { getCurrentUser } from '@/lib/auth';
import { checkPurchaseDate } from '@/lib/purchase-guard';
// The "one item = one line on a bill" remedy sentence is SHARED, not restated:
// the PO routes, the bill modal and POST /api/purchases already print it
// verbatim, and a storekeeper who is told one thing on screen and another in a
// skipped-rows CSV has been told nothing. line-dedupe imports nothing, so this
// costs the bundle nothing. Edit it there or not at all.
import { SPLIT_RATE_REMEDY } from '@/lib/line-dedupe';

interface BulkPurchaseItem {
  item_name: string;
  /** Preferred match key — unique across the whole catalogue. */
  sku?: string;
  vendor?: string;
  brand?: string;
  quantity: number;
  unit_price: number;
  total_amount?: number;
  date: string;
  notes?: string;
  gst_amount?: number;
  /** The VENDOR's own bill number (from the physical bill). Our Invoice ID is
   *  generated by the server — it is never taken from the upload. */
  bill_no?: string;
  /** Inward-sheet columns. purchase_unit is VERIFIED against the material's
   *  configured purchase unit (a mismatch would silently mis-book stock);
   *  category_name is informational; po_qty is recorded. */
  purchase_unit?: string;
  category_name?: string;
  po_qty?: number;
  // GRN-Inward per-line charges (₹) — recorded only, never change unit cost.
  // compensation_cess is GST Compensation Cess, a DIFFERENT levy from
  // special_excise_cess (TGBCL Special Excise Cess). It arrives here as a plain
  // rupee figure and is stored as one: this importer never derives it from
  // raw_materials.cess_percent — a sheet states what the vendor actually
  // charged, and re-deriving it from a master rate would overwrite the bill.
  // It is NOT part of the house invariant tax_value === cgst + sgst either;
  // cess is never halved and adding it to that sum overstates GST on a return.
  discount?: number; cgst?: number; sgst?: number; compensation_cess?: number;
  special_excise_cess?: number; tcs?: number; delivery_charges?: number; mrp_round_off?: number;
}

/** One rejected row, echoed back with enough to re-download + fix + re-upload. */
type SkipKind = 'missing' | 'date' | 'not_found' | 'liquor' | 'invalid' | 'duplicate' | 'unit_mismatch';
interface SkippedRow {
  row: number;
  item_name: string; sku: string; vendor: string; brand: string;
  quantity: any; unit_price: any; total_amount: any; gst_amount: any;
  date: string; notes: string; bill_no: string;
  category_name: string; po_qty: any; purchase_unit: string;
  discount: any; cgst: any; sgst: any; compensation_cess: any;
  special_excise_cess: any; tcs: any; delivery_charges: any; mrp_round_off: any;
  kind: SkipKind; reason: string;
}
/** Per-line charge coercion. mrp_round_off is signed; the rest ≥ 0. */
const chg = (v: any) => { const x = Number(v); return Number.isFinite(x) && x > 0 ? Math.round(x * 100) / 100 : 0; };
const chgSigned = (v: any) => { const x = Number(v); return Number.isFinite(x) ? Math.round(x * 100) / 100 : 0; };
/** ₹ for a human-readable skip reason — the same shape POST /api/purchases
 *  prints in its 409, so the two refusals read alike. */
const inr = (n: number) => `₹${Number(n).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export async function POST(request: Request) {
  try {
    // AUTH GATE — same one POST /api/grn and POST /api/purchases already have.
    // This handler read the session ONLY to decide the admin backdate exemption
    // (`isAdmin` below) and never rejected an anonymous caller. proxy.ts step 2c
    // does validate the session token for mutating API calls, but that check is
    // wrapped in try/catch and falls OPEN on a DB/infra error — so it must not be
    // the only thing standing between an unauthenticated caller and a bulk import
    // that bumps stock, writes purchases rows and lets updateMaterialPrice rewrite
    // average_price through every recipe built on those materials. Resolve the
    // session once here and reuse it for the backdate rule.
    const me = await getCurrentUser();
    if (!me) return Response.json({ error: 'Sign in required' }, { status: 401 });
    const isAdmin = me.role === 'admin';

    const db = getDb();
    const body = await request.json();
    const { purchases } = body as { purchases: BulkPurchaseItem[] };

    if (!purchases || !Array.isArray(purchases) || purchases.length === 0) {
      return Response.json({ error: 'purchases array is required' }, { status: 400 });
    }

    const allMaterials = db.prepare('SELECT id, name, sku, unit, purchase_unit, pack_size, category FROM raw_materials').all() as any[];
    // Match by SKU FIRST, then name. SKUs are unique across the whole catalogue
    // (grocery + liquor) and are stable, whereas a name can be renamed or carry
    // a typo — so a sheet that supplies `sku` always resolves to the right item.
    const materialMap = new Map<string, any>();
    const skuMap = new Map<string, any>();
    for (const m of allMaterials) {
      materialMap.set(m.name.toLowerCase().trim(), m);
      const s = String(m.sku || '').toLowerCase().trim();
      if (s) skuMap.set(s, m);
    }

    const toStockQty = (m: any, qty: number) => {
      const packSize = Number(m.pack_size) || 1;
      const ru = String(m.unit || '').toLowerCase().trim();
      const pu = String(m.purchase_unit || m.unit || '').toLowerCase().trim();
      return (packSize > 1 && ru !== pu) ? qty * packSize : qty;
    };

    const results: {
      success: number; skipped: number; duplicates: number;
      errors: string[];
      store_blocked: Array<{ material: string; error: string }>;
      skipped_rows: SkippedRow[];
    } = { success: 0, skipped: 0, duplicates: 0, errors: [], store_blocked: [], skipped_rows: [] };

    // Record a skipped row into every reporting channel (back-compat + the new
    // detailed list the UI shows + lets the user download).
    const skip = (item: BulkPurchaseItem, rowNum: number, kind: SkipKind, reason: string) => {
      results.skipped++;
      if (kind === 'duplicate') results.duplicates++;
      results.errors.push(`Row ${rowNum}: ${reason}`);
      if (kind === 'liquor') results.store_blocked.push({ material: item.item_name || '', error: reason });
      results.skipped_rows.push({
        row: rowNum,
        item_name: item.item_name || '', sku: item.sku || '', vendor: item.vendor || '', brand: item.brand || '',
        quantity: item.quantity ?? '', unit_price: item.unit_price ?? '',
        total_amount: item.total_amount ?? '', gst_amount: item.gst_amount ?? '',
        date: item.date || '', notes: item.notes || '', bill_no: item.bill_no || '',
        category_name: item.category_name || '', po_qty: item.po_qty ?? '', purchase_unit: item.purchase_unit || '',
        discount: item.discount ?? '', cgst: item.cgst ?? '', sgst: item.sgst ?? '',
        compensation_cess: item.compensation_cess ?? '',
        special_excise_cess: item.special_excise_cess ?? '', tcs: item.tcs ?? '',
        delivery_charges: item.delivery_charges ?? '', mrp_round_off: item.mrp_round_off ?? '',
        kind, reason,
      });
    };

    const insertPurchase = db.prepare(`
      INSERT INTO purchases (id, material_id, vendor, brand, quantity, unit_price, total_price, date, notes, invoice_id, bill_no,
                             discount, cgst, sgst, compensation_cess, special_excise_cess, tcs, delivery_charges, mrp_round_off, po_qty, created_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
    `);

    // ── Invoice ID (OUR number) — auto-generated, never taken from the upload.
    // Format PINV-<year>-#### continuing from the highest existing number.
    // Lines of the SAME vendor bill (vendor + bill_no + date) share ONE
    // invoice_id; rows with no bill_no each get their own (we can't know they
    // belong together). Distinct from bill_no, the vendor's own bill number.
    const yr = new Date().getFullYear();
    // MAX on the NUMERIC suffix — a string sort would rank 'PINV-2026-9999'
    // above 'PINV-2026-10000' once the year passes 9,999 lines and reuse ids.
    const lastInv = db.prepare(
      `SELECT MAX(CAST(substr(invoice_id, length('PINV-' || ? || '-') + 1) AS INTEGER)) AS n
       FROM purchases WHERE invoice_id LIKE 'PINV-' || ? || '-%'`
    ).get(String(yr), String(yr)) as any;
    let invSeq = Number(lastInv?.n) || 0;
    const invoiceIdByBill = new Map<string, string>();
    // The memo Map is request-scoped, so a bill split across TWO uploads (a line
    // was missed, corrected, or split by department) would otherwise mint a
    // second id for the same physical bill. Look the bill up in the DB first.
    // COALESCE(invoice_id,'') <> '' is load-bearing: manual / GRN / PO-receive
    // rows share vendor+bill+date with an EMPTY invoice_id and must not match.
    const invoiceIdForBill = db.prepare(`
      SELECT invoice_id FROM purchases
      WHERE COALESCE(invoice_id, '') <> ''
        AND LOWER(TRIM(COALESCE(vendor, ''))) = ?
        AND LOWER(TRIM(COALESCE(bill_no, ''))) = ?
        AND date = ?
      LIMIT 1
    `);
    const mintInvoiceId = () => {
      invSeq += 1;
      return `PINV-${yr}-${String(invSeq).padStart(4, '0')}`;
    };
    const nextInvoiceId = (vendor: string, billNo: string, date: string) => {
      // No bill number → we can't know which lines belong together; solo id.
      if (!billNo) return mintInvoiceId();
      const v = (vendor || '').toLowerCase().trim();
      const b = billNo.toLowerCase().trim();
      const key = `${v}|${b}|${date}`;
      const memo = invoiceIdByBill.get(key);
      if (memo) return memo;
      const prior = invoiceIdForBill.get(v, b, date) as { invoice_id?: string } | undefined;
      const id = prior?.invoice_id || mintInvoiceId();
      invoiceIdByBill.set(key, id);
      return id;
    };
    const updateStock = db.prepare(`
      UPDATE raw_materials SET current_stock = current_stock + ?, updated_at = datetime('now') WHERE id = ?
    `);
    const insertTransaction = db.prepare(`
      INSERT INTO inventory_transactions (id, material_id, type, quantity, reference_id, notes, created_at)
      VALUES (?, ?, 'purchase', ?, ?, ?, datetime('now'))
    `);
    // Duplicate guard: same material + vendor + date + qty + unit_price already
    // in the DB, with the VENDOR's bill_no as an ADDITIONAL discriminator (never
    // our auto invoice_id, which is unique per entry and would defeat the check).
    //
    // A STORED row with an EMPTY bill_no matches ANY incoming bill_no. That is
    // load-bearing: every pre-existing row, and every row written by the single
    // POST / opening-stock / GRN / PO-receive / inward-import paths, has
    // bill_no ''. Comparing strictly would make them invisible the moment the
    // user starts filling the new bill_no column — the same file re-uploaded
    // would insert again and DOUBLE the stock. Two genuine lines that differ
    // only by a NON-empty bill number are still both kept.
    const dupCheck = db.prepare(`
      SELECT 1 FROM purchases
      WHERE material_id = ?
        AND LOWER(COALESCE(vendor, '')) = LOWER(?)
        AND (COALESCE(bill_no, '') = '' OR LOWER(bill_no) = LOWER(?))
        AND date = ?
        AND ROUND(quantity, 3)   = ROUND(?, 3)
        AND ROUND(unit_price, 2) = ROUND(?, 2)
      LIMIT 1
    `);

    // ── ONE MATERIAL = ONE LINE ON A NAMED BILL. The rule /api/purchase-orders
    // has always had and that POST /api/purchases took on when the owner said
    // "YES WANT LIKE PO". Identity is material_id ALONE, scoped to one document.
    //
    // WHY THIS IS A SECOND STATEMENT AND NOT A WIDENING OF dupCheck ABOVE: that
    // one carries the empty-bill WILDCARD, and THE WILDCARD MUST NEVER BE
    // COMBINED WITH A MATERIAL-LEVEL KEY. Behind qty AND rate the wildcard can
    // only ever match a genuinely identical line, which is what makes it safe.
    // Widen the key to the material and it inverts into data loss: a stored
    // blank-bill row for item X on date D would swallow a legitimately different
    // bill for X that day, and two real same-day market runs for one item would
    // collapse into one. So this statement matches bill_no EXACTLY — scoped to a
    // named document, a stored blank-bill row is BY DEFINITION a different
    // document — and the wildcard stays where it is, in dupCheck.
    //
    // WHAT IS DELIBERATELY *NOT* COPIED from POST /api/purchases' 409 query: its
    // `invoice_id LIKE 'PINV-%'` scope test and its po_qty / special_excise_cess
    // / tcs / mrp_round_off zero tests. That route wrote none of those columns,
    // so excluding such rows only kept it off other flows' toes. THIS importer
    // writes all of them, so the same filters would make a re-uploaded inward
    // sheet invisible to its own guard and double the stock — the one failure
    // this file exists to prevent.
    const billLineCheck = db.prepare(`
      SELECT quantity, unit_price, COALESCE(invoice_id, '') AS invoice_id
      FROM purchases
      WHERE material_id = ?
        AND LOWER(TRIM(COALESCE(vendor, ''))) = ?
        AND LOWER(TRIM(COALESCE(bill_no, ''))) = ?
        AND date = ?
      ORDER BY created_at ASC
      LIMIT 1
    `);

    const touchedMaterials = new Set<string>();
    // Also dedupe WITHIN the uploaded file (same row twice in one upload) — one
    // set per branch, mirroring the two DB checks. seenBillItem remembers the
    // 1-based row number so the skip reason can point at the earlier line.
    const seenInFile = new Set<string>();
    const seenBillItem = new Map<string, number>();
    const dupKey = (mid: string, vendor: string, billNo: string, date: string, q: number, up: number) =>
      `${mid}|${(vendor || '').toLowerCase().trim()}|${(billNo || '').toLowerCase().trim()}|${date}|${Math.round(q * 1000)}|${Math.round(up * 100)}`;

    const batchInsert = db.transaction(() => {
      for (let i = 0; i < purchases.length; i++) {
        const item = purchases[i];
        const rowNum = i + 1;

        const rowSku = String(item.sku || '').toLowerCase().trim();
        if ((!item.item_name && !rowSku) || (!item.quantity && !item.total_amount) || (!item.unit_price && !item.total_amount)) {
          skip(item, rowNum, 'missing', `Missing required fields (sku or item_name / quantity / price)`);
          continue;
        }
        const dateCheck = checkPurchaseDate(db, item.date, isAdmin);
        if (!dateCheck.ok) { skip(item, rowNum, 'date', dateCheck.error || 'Invalid date'); continue; }

        // SKU wins over name — it's unique and immune to renames/typos.
        const mat = (rowSku && skuMap.get(rowSku))
          || (item.item_name ? materialMap.get(item.item_name.toLowerCase().trim()) : undefined);
        if (!mat) {
          skip(item, rowNum, 'not_found',
            `Material not found: "${item.sku || item.item_name}" — the sku (preferred) or name must match an existing Raw Material.`);
          continue;
        }
        const materialId = mat.id;

        const storeMsg = centralFlowBlock(db, materialId);
        if (storeMsg) { skip(item, rowNum, 'liquor', storeMsg); continue; }

        // PURCHASE UNIT guard. `quantity` is ALWAYS in the material's configured
        // purchase unit. If the sheet names a different unit (e.g. "CASE" when
        // the item is set up in "BTL", or the recipe unit "g" instead of "kg"),
        // booking it as-is would silently mis-state stock by the pack factor —
        // so skip and report instead of guessing. Blank = trust the config.
        const sheetUnit = String(item.purchase_unit || '').trim();
        if (sheetUnit) {
          const configured = String(mat.purchase_unit || '').trim() || String(mat.unit || '').trim();
          if (configured && sheetUnit.toLowerCase() !== configured.toLowerCase()) {
            skip(item, rowNum, 'unit_mismatch',
              `Purchase unit mismatch for "${mat.name}": the sheet says "${sheetUnit}" but the item is set up in "${configured}". `
              + `Quantity must be in "${configured}" — fix the sheet (or the item's purchase unit) and re-upload.`);
            continue;
          }
        }

        let quantity = Number(item.quantity) || 0;
        let unitPrice = Number(item.unit_price) || 0;
        const totalAmount = Number(item.total_amount) || 0;
        const gstAmount = Number(item.gst_amount) || 0;
        // CONTRACT: total_amount is the CHARGE-FREE line amount (qty × rate).
        // It must NOT be the charge-inclusive "Total Inward Amount" — the 7
        // charges are stored separately, so folding them in here would bake
        // them into the weighted-average cost AND count them twice. The client
        // parser backs charges out before sending (see purchases/page.tsx).
        //
        // gst_amount is DELIBERATELY absent from this derivation. GST is a
        // reclaimable input credit and must never enter unit_price: this loop
        // ends in updateMaterialPrice(), which averages SUM(qty × unit_price)
        // / SUM(qty) into average_price, which every recipe cost is built on.
        // Adding it here inflates the cost of every dish that uses the item —
        // the exact failure that got the bill-level GST control deleted. The
        // rate is the rate; tax travels BESIDE it in cgst/sgst below. Do not
        // "restore" the old gross-up folds, and do not add a second branch that
        // grosses up a supplied unit_price by the tax.
        if (totalAmount > 0 && unitPrice === 0 && quantity > 0) {
          unitPrice = Math.round((totalAmount / quantity) * 100) / 100;
        }
        if (quantity <= 0 || unitPrice <= 0) {
          skip(item, rowNum, 'invalid', `Invalid quantity or price for "${item.item_name}"`);
          continue;
        }

        const billNo = String(item.bill_no || '').trim();
        const vendorKey = String(item.vendor || '').toLowerCase().trim();
        const vendorLabel = String(item.vendor || '').trim() || 'this vendor';

        /* ── DUPLICATE GUARD, TWO BRANCHES. Which one applies is decided by the
         * INCOMING row, because that is what decides whether there is a document
         * to judge against. Both SKIP the row; neither fails the upload. A sheet
         * is hundreds of rows and the recovery-CSV flow is built on per-row
         * skips — failing 500 rows because row 300 repeats would take that away.
         * The reason string IS the product here, so it names the row, the item,
         * the bill and what to do instead.
         *
         *  A · bill_no PRESENT → a bill is a document and one item appears on it
         *      once. Judge at MATERIAL level against that same named bill, and
         *      the same way within this sheet. billLineCheck has no wildcard, on
         *      purpose — see the note over it; the wildcard and a material-level
         *      key together are the trap.
         *  B · bill_no BLANK → no document identity at all. Two market runs for
         *      one item from one vendor on one day are two real purchases, so
         *      the only thing honestly on offer is re-upload protection: the
         *      six-part exact match, wildcard and all, unchanged. This is the
         *      same carve-out POST /api/purchases makes.
         *
         * BRANCH A DOES NOT REPLACE THE SIX-PART CHECK — it runs BEFORE it, and
         * a named-bill row still falls through to it. Skipping it for named
         * bills would reopen the exact hole the wildcard exists to plug: a sheet
         * first uploaded with the bill_no column empty stores rows with bill_no
         * '', and the same sheet re-uploaded once the numbers are filled in
         * would find no named-bill match and book every line's goods a second
         * time. So the set of rows caught here is a strict SUPERSET of what was
         * caught before this change. Keep it that way. */
        const key = dupKey(materialId, item.vendor || '', billNo, item.date, quantity, unitPrice);
        const billItemKey = `${materialId}|${vendorKey}|${billNo.toLowerCase()}|${item.date}`;

        if (billNo) {
          const priorRow = seenBillItem.get(billItemKey);
          if (priorRow !== undefined) {
            skip(item, rowNum, 'duplicate',
              `"${mat.name}" is already on bill ${billNo} from ${vendorLabel} dated ${item.date} — row ${priorRow} of this sheet. `
              + `One item = one line on a bill, so row ${rowNum} was NOT imported. ${SPLIT_RATE_REMEDY}`);
            continue;
          }
          const prior = billLineCheck.get(materialId, vendorKey, billNo.toLowerCase(), item.date) as
            { quantity: number; unit_price: number; invoice_id: string } | undefined;
          if (prior) {
            skip(item, rowNum, 'duplicate',
              `"${mat.name}" is already recorded on bill ${billNo} from ${vendorLabel} dated ${item.date} — `
              + `${prior.quantity} @ ${inr(prior.unit_price)}${prior.invoice_id ? ` (${prior.invoice_id})` : ''}. `
              + `One item = one line on a bill, so row ${rowNum} was NOT imported. ${SPLIT_RATE_REMEDY}`);
            continue;
          }
        }

        const already = seenInFile.has(key) || !!dupCheck.get(materialId, item.vendor || '', billNo, item.date, quantity, unitPrice);
        if (already) {
          skip(item, rowNum, 'duplicate',
            `"${mat.name}"${billNo ? ` (bill ${billNo})` : ''} from ${vendorLabel} dated ${item.date} — `
            + `already uploaded: same item + vendor + bill no + date + qty (${quantity}) + rate (${inr(unitPrice)}). `
            + `Row ${rowNum} was skipped so the stock is not counted twice.`);
          continue;
        }
        seenInFile.add(key);
        if (billNo) seenBillItem.set(billItemKey, rowNum);

        // `quantity` is PURCHASE units by contract, enforced twice in this route: the
        // sheet's purchase_unit column must equal the material's configured purchase
        // unit or the row is skipped (line 288-296), and the stock credit below is
        // toStockQty(mat, quantity) = qty × pack_size, i.e. it treats qty as purchase
        // units to reach recipe units. `unitPrice` is the sheet rate (or totalAmount ÷
        // quantity, same basis) and goes straight into purchases.unit_price = ₹ per
        // PURCHASE unit by canon; updateMaterialPrice() later divides it by pack_size
        // to get ₹/recipe-unit. So total_price = purchase qty × ₹/purchase unit.
        // rate-basis: purchase
        const totalPrice = Math.round(quantity * unitPrice * 100) / 100;

        // A sheet's single `gst_amount` column becomes the CGST/SGST pair, so the
        // credit is recorded beside the goods rate instead of inside it. Split in
        // integer paise — halving in floats drifts a paisa and breaks the house
        // invariant tax = cgst + sgst that every reader re-adds — with the odd
        // paisa landing in CGST. This is character-for-character the split used by
        // POST /api/purchases and by the /purchases client preview; changing it on
        // one side alone makes the preview and the stored row disagree by ₹0.01.
        // If the sheet already itemised cgst/sgst, gst_amount is IGNORED: the tax
        // is already booked and adding it again would double the input credit.
        let cgstOut = chg(item.cgst), sgstOut = chg(item.sgst);
        if (gstAmount > 0 && cgstOut === 0 && sgstOut === 0) {
          const taxPaise = Math.round(gstAmount * 100);
          sgstOut = Math.floor(taxPaise / 2) / 100;
          cgstOut = Math.round((gstAmount - sgstOut) * 100) / 100;
        }

        const id = generateId();
        const invoiceId = nextInvoiceId(item.vendor || '', billNo, item.date);
        insertPurchase.run(id, materialId, item.vendor || '', item.brand || '', quantity, unitPrice, totalPrice, item.date, item.notes || '', invoiceId, billNo,
          chg(item.discount), cgstOut, sgstOut, chg(item.compensation_cess),
          chg(item.special_excise_cess), chg(item.tcs), chg(item.delivery_charges), chgSigned(item.mrp_round_off),
          chg(item.po_qty));
        const stockQty = toStockQty(mat, quantity);
        updateStock.run(stockQty, materialId);
        insertTransaction.run(generateId(), materialId, stockQty, id, `Bulk import: ${item.vendor || 'unknown'}`);
        touchedMaterials.add(materialId);
        results.success++;
      }
    });
    batchInsert();

    for (const materialId of touchedMaterials) updateMaterialPrice(db, materialId);

    return Response.json(results, { status: 200 });
  } catch (error: any) {
    return Response.json({ error: error.message }, { status: 500 });
  }
}
